# fill out and rename to settings.yaml (in gitignore)
cloudinary:
  cloud_name: ''
  api_key: ''
  api_secret: ''
mail:
  smtp: ''
  from: ''
postgre:
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''
redis:
  port: ''
  pass: ''
  host: ''
sessions:
  secret: ''
admin:
  username: ''
  password: ''
  email: ''
crypto:
  digest: ''
  iterations: 1
url: ''
